---
development:
  cloud_name: lananhhy
  api_key: '924418495187684'
  api_secret: Oh16Lz9wmD0b_4XrcTUZojxpJ3A
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: lananhhy
  api_key: '924418495187684'
  api_secret: Oh16Lz9wmD0b_4XrcTUZojxpJ3A
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: lananhhy
  api_key: '924418495187684'
  api_secret: Oh16Lz9wmD0b_4XrcTUZojxpJ3A
  enhance_image_tag: true
  static_image_support: false
